PRAGMA synchronous = OFF;
PRAGMA journal_mode = MEMORY;
BEGIN TRANSACTION;
CREATE TABLE `KnowledgeItem` (
  `id` INTEGER NULL  DEFAULT NULL,
  `title` CHAR(200) NULL DEFAULT NULL,
  `text` MEDIUMTEXT(20000) NULL DEFAULT NULL,
  `publish_time` DATETIME NULL DEFAULT NULL,
  `owner` INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);
CREATE TABLE `User` (
  `id` INTEGER NULL  DEFAULT NULL,
  `username` CHAR(100) NULL DEFAULT NULL,
  `password` VARCHAR(400) NULL DEFAULT NULL,
  `name` VARCHAR(400) NULL DEFAULT NULL,
  `family` CHAR(400) NULL DEFAULT NULL,
  `email` CHAR(500) NULL DEFAULT NULL,
  `admin` bit NOT NULL DEFAULT 0,
  `national_code` CHAR(10) NULL DEFAULT NULL,
  `personel_code` CHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);
CREATE TABLE `Tag` (
  `id` INTEGER NULL  DEFAULT NULL,
  `text` CHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);
CREATE TABLE `KnowledgeTag` (
  `id` INTEGER NULL  DEFAULT NULL,
  `KnwoledgeItemID` INTEGER NOT NULL DEFAULT NULL,
  `TagID` INTEGER NOT NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);
CREATE TABLE `File` (
  `id` INTEGER NULL  DEFAULT NULL,
  `path` CHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);
CREATE TABLE `KnowledgeFile` (
  `id` INTEGER NULL  DEFAULT NULL,
  `KnowledgeItemID` INTEGER NOT NULL DEFAULT NULL,
  `FileID` INTEGER NOT NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);
END TRANSACTION;

